import React from 'react';
import ReactDOM from 'react-dom/client';

const Title = () => (
  <a href="/">
    <img
      alt="Tasty Delights Logo"
      className="logo"
      src="https://scontent.fhyd2-1.fna.fbcdn.net/v/t39.30808-6/243074583_280245397287740_7524579202904818768_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=ibA-3TtEjBsAX9ru3Ny&_nc_ht=scontent.fhyd2-1.fna&oh=00_AfAGXxnb5fpdWc9lZQD69DNVuhG36MBDbLoqnb8iROKGcQ&oe=64C2EE90"
    />
  </a>
);

const Header = () => {
  return (
    <div className="header">
      <Title />
      <div className="nav__items">
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Contact</li>
          <li>Cart</li>
        </ul>
      </div>
    </div>
  );
};

// Config Driven UI

const restaurantList = [
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '4320',
      name: 'Mehfil',
      uuid: '4dee4970-8673-42b6-8a49-cab0efdb258f',
      city: '3',
      area: 'Narayanguda',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'esp0fhddgfgdss5hyhpi',
      cuisines: ['Biryani', 'North Indian', 'Tandoor', 'Chinese', 'Kebabs'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 23,
      minDeliveryTime: 23,
      maxDeliveryTime: 23,
      slaString: '23 MINS',
      lastMileTravel: 2,
      slugs: {
        restaurant: 'mehfil-narayanguda-himayath-nagar',
        city: 'hyderabad',
      },
      cityState: '3',
      address: 'Near Narayanguda Flyover, Narayanguda, Hyderabad',
      locality: 'Near Narayanguda Flyover',
      parentId: 637,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7488554~p=1~eid=00000189-879c-0dcc-0030-ddc100f9012f~srvts=1690197298636',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '2 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '10% OFF',
        subHeader: 'UPTO ₹40',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '4320',
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        lastMileTravel: 2,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '3.9',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '403007',
      name: "Haldiram's Sweets and Namkeen",
      uuid: '08a4d4d4-2093-4535-a7e5-21d59d6f26a3',
      city: '3',
      area: 'Himayath Nagar',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: 'edf8410c87fc2a56e2e047bec146702b',
      cuisines: ['Sweets', 'Bakery', 'Desserts'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 20,
      minDeliveryTime: 20,
      maxDeliveryTime: 20,
      slaString: '20 MINS',
      lastMileTravel: 1.399999976158142,
      slugs: {
        restaurant:
          'haldirams-sweets-and-namkeen-himayath-nagar-himayath-nagar',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        '5-2-1070/1-10, Shop no.2 to 4, Ground floor, Moti Mahal Market, Nizam Sahi Road, Abids, Hyderabad',
      locality: 'Ground floor, Moti Mahal Market',
      parentId: 391465,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.3 kms',
      hasSurge: false,
      sla: {
        restaurantId: '403007',
        deliveryTime: 20,
        minDeliveryTime: 20,
        maxDeliveryTime: 20,
        lastMileTravel: 1.399999976158142,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.2',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '4138',
      name: 'Grand Hotel',
      uuid: 'c1a1d888-51b7-4bcc-b539-f884c796a015',
      city: '3',
      area: 'Koti',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'g1arzw6qd7g9affkmgzk',
      cuisines: ['Biryani', 'Chinese', 'Tandoor', 'Haleem'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 22,
      minDeliveryTime: 22,
      maxDeliveryTime: 22,
      slaString: '22 MINS',
      lastMileTravel: 1.2000000476837158,
      slugs: {
        restaurant: 'grand-hotel-abids-himayath-nagar',
        city: 'hyderabad',
      },
      cityState: '3',
      address: 'Opposite Big Bazaar, 4-1-395,Abids Road, Hyderabad',
      locality: 'Abids Road',
      parentId: 4001,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7488565~p=4~eid=00000189-879c-0dcc-0030-ddc200f90433~srvts=1690197298636',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.2 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '10% OFF',
        subHeader: 'UPTO ₹40',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '4138',
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        lastMileTravel: 1.2000000476837158,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.1',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '4650',
      name: 'Bawarchi',
      uuid: '4e784916-87ff-4951-9c21-2f0c1df1fb31',
      city: '3',
      area: 'New Nallakunta',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'smfhai0o8rnjuzp3ngxu',
      cuisines: [
        'Biryani',
        'Tandoor',
        'Chinese',
        'Indian',
        'Desserts',
        'Kebabs',
        'Mughlai',
      ],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 31,
      minDeliveryTime: 31,
      maxDeliveryTime: 31,
      slaString: '31 MINS',
      lastMileTravel: 3,
      slugs: {
        restaurant: 'bawarchi-nallakunta-vidyanagar',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        'Beside Astoria Hotel, RTC Cross Road, Chikkadpally, Nallakunta, Hyderabad',
      locality: 'New Nallakunta',
      parentId: 100,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 3500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3500,
        message: '',
        title: 'Delivery Charge',
        amount: '3500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '3 kms',
      hasSurge: false,
      sla: {
        restaurantId: '4650',
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.0',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '367769',
      name: 'Lucky Restaurant',
      uuid: '0d2cb79c-7f66-4009-b393-3f9015ba849d',
      city: '3',
      area: 'MasabTank',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'qems028i3da5rxf81rbp',
      cuisines: ['Biryani', 'North Indian', 'Tandoor'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 48,
      minDeliveryTime: 48,
      maxDeliveryTime: 48,
      slaString: '48 MINS',
      lastMileTravel: 5,
      slugs: {
        restaurant: 'lucky-restaurant-banjara-hills-banjara-hills',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        'Dana Chambers, Saifabad Rd, Sham Nagar Colony, Chintal, Hyderabad, Telangana 500004',
      locality: 'Banjara Hills',
      parentId: 293683,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 5400,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 5400,
        message: '',
        title: 'Delivery Charge',
        amount: '5400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '5 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '30% OFF',
        subHeader: 'UPTO ₹75',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '367769',
        deliveryTime: 48,
        minDeliveryTime: 48,
        maxDeliveryTime: 48,
        lastMileTravel: 5,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.9',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '17104',
      name: 'KFC',
      uuid: 'f08de782-23c6-4f4c-95f4-f26eeb368a5e',
      city: '3',
      area: 'Himayatnagar',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: '56c9ab92bd79745fd152a30fa2525426',
      cuisines: ['Burgers', 'Biryani', 'American', 'Snacks', 'Fast Food'],
      tags: [],
      costForTwo: 40000,
      costForTwoString: '₹400 FOR TWO',
      deliveryTime: 27,
      minDeliveryTime: 27,
      maxDeliveryTime: 27,
      slaString: '27 MINS',
      lastMileTravel: 2.5999999046325684,
      slugs: {
        restaurant: 'kfc-himayathnagar-himayath-nagar',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        'KFC Restaurant (Himayathnagar),The Brand Factory Building Plot No. 3-6-552 to 558/1 MPM Millennium, Wajhuddin Estate, Opp. Minerva, Advocates Colony, Himayath Nagar Hyderabad, Telangana 500029 India',
      locality: 'Prime Plaza',
      parentId: 547,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7354312~p=7~eid=00000189-879c-0dcc-0030-ddc300f90779~srvts=1690197298636',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '2.5 kms',
      hasSurge: false,
      sla: {
        restaurantId: '17104',
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        lastMileTravel: 2.5999999046325684,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.0',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '131870',
      name: '4M Biryani House',
      uuid: '3b8256f4-4e99-4cdf-8b9e-9dbd267af08a',
      city: '3',
      area: 'Musheerabad',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'o685uklvqias8ez1qgxz',
      cuisines: ['Biryani', 'Tandoor', 'Chinese', 'North Indian'],
      tags: [],
      costForTwo: 25000,
      costForTwoString: '₹250 FOR TWO',
      deliveryTime: 36,
      minDeliveryTime: 36,
      maxDeliveryTime: 36,
      slaString: '36 MINS',
      lastMileTravel: 4.300000190734863,
      slugs: {
        restaurant: '4m-biryani-house-musheerabad-nallakunta-vidyanagar',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        'Opposite Humera Hotel, Badi Masjid, Bholakpur, Musheerabad, Hyderabad',
      locality: '',
      parentId: 19646,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 4100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4100,
        message: '',
        title: 'Delivery Charge',
        amount: '4100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '4.3 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '30% OFF',
        subHeader: 'UPTO ₹75',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '131870',
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        lastMileTravel: 4.300000190734863,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '547809',
      name: 'Theobroma',
      uuid: 'e6303a6e-b41d-4041-8f9c-dde9d3986000',
      city: '3',
      area: 'Himayath Nagar',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: 'wxr6gobr4fbwrp3j91dt',
      cuisines: ['Desserts'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      slaString: '28 MINS',
      lastMileTravel: 3,
      slugs: {
        restaurant: 'theobroma-himayath-nagar-himayath-nagar',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        '3-6-138/5 & 6, GROUND FLOOR, PAPALAL CHAMBERS, HIMAYATNAGAR Circle, Hyderabad, Telangana   500029',
      locality: 'Papalal Chambers',
      parentId: 1040,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 3500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3500,
        message: '',
        title: 'Delivery Charge',
        amount: '3500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7564807~p=10~eid=00000189-879c-0dcc-0030-ddc400f90a73~srvts=1690197298636',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '3 kms',
      hasSurge: false,
      sla: {
        restaurantId: '547809',
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.4',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '109168',
      name: 'Al Rabea Al Arabi Cafeteria',
      uuid: 'f94c1d30-76b4-438a-bddf-6442286fbb6e',
      city: '3',
      area: 'Santosh Nagar',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'lu7b9y7xps4icwn6xzfj',
      cuisines: ['Lebanese', 'Arabian'],
      tags: [],
      costForTwo: 25000,
      costForTwoString: '₹250 FOR TWO',
      deliveryTime: 29,
      minDeliveryTime: 29,
      maxDeliveryTime: 29,
      slaString: '29 MINS',
      lastMileTravel: 6.300000190734863,
      slugs: {
        restaurant:
          'al-rabea-al-arabi-cafeteria-santhosh-nagar-santoshnagar-saidabad',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        '9-8-118 BESIDE JB NASHTA POINT SANTOSH NAGAR OPPOSITE LUCKY HOTEL  HYDERABAD',
      locality: 'Opposite Lucky Hotel',
      parentId: 7582,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 6000,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 6000,
        message: '',
        title: 'Delivery Charge',
        amount: '6000',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '6.3 kms',
      hasSurge: false,
      sla: {
        restaurantId: '109168',
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        lastMileTravel: 6.300000190734863,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.3',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '142670',
      name: 'Shah Ghouse Cafe & Restaurant',
      uuid: '88b357e6-6560-449b-9400-5e9a9915db66',
      city: '3',
      area: 'Lakdikapul',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'bk26jkkqpg55veii0aj9',
      cuisines: ['Biryani', 'Chinese', 'Tandoor', 'Mughlai', 'North Indian'],
      tags: [],
      costForTwo: 35000,
      costForTwoString: '₹350 FOR TWO',
      deliveryTime: 42,
      minDeliveryTime: 42,
      maxDeliveryTime: 42,
      slaString: '42 MINS',
      lastMileTravel: 4.199999809265137,
      slugs: {
        restaurant: 'shah-ghouse-cafe-restaurant-lakdikapool-nampally',
        city: 'hyderabad',
      },
      cityState: '3',
      address: '6-2-971,Lakdikapool,Hyd',
      locality: 'Santh Nirankari Satsang Bhavan',
      parentId: 18992,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 4100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4100,
        message: '',
        title: 'Delivery Charge',
        amount: '4100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7364358~p=13~eid=00000189-879c-0dcc-0030-ddc500f90d13~srvts=1690197298636',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '4.1 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '30% OFF',
        subHeader: 'UPTO ₹75',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '142670',
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        lastMileTravel: 4.199999809265137,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.1',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '100942',
      name: 'Lucky Multicuisine Restaurant',
      uuid: '8e677eb2-065e-4021-ab21-b94d70357977',
      city: '3',
      area: 'Somajiguda',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'yeyiqeakfhjj6cmeocsc',
      cuisines: ['Biryani', 'North Indian', 'Tandoor', 'South Indian'],
      tags: [],
      costForTwo: 35000,
      costForTwoString: '₹350 FOR TWO',
      deliveryTime: 43,
      minDeliveryTime: 43,
      maxDeliveryTime: 43,
      slaString: '43 MINS',
      lastMileTravel: 6.400000095367432,
      slugs: {
        restaurant:
          'lucky-multicuisine-restaurant-somajiguda-somajiguda-khairtabad',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        'Door no;6-3-1089/f/33,somajiguda,hyd,circle no.10(old mch circle-v)khairtabad,hyd-central zone, telengana 500082.',
      locality: '\nRaj Bhavan Quarters Colony',
      parentId: 18963,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 6000,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 6000,
        message: '',
        title: 'Delivery Charge',
        amount: '6000',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 1,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '6.4 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '50% OFF',
        subHeader: 'UPTO ₹100',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '100942',
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        lastMileTravel: 6.400000095367432,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'IT_IS_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.7',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '700497',
      name: 'Pista House Restaurant & Bakery',
      uuid: 'be06298d-08f8-4cd9-b087-20f3df79718b',
      city: '3',
      area: 'Gaddiannaram',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: '8897124781976e694d84046bd90f7270',
      cuisines: [
        'Biryani',
        'North Indian',
        'Chinese',
        'Kebabs',
        'Tandoor',
        'Desserts',
      ],
      tags: [],
      costForTwo: 50000,
      costForTwoString: '₹500 FOR TWO',
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      slaString: '26 MINS',
      lastMileTravel: 4.599999904632568,
      slugs: {
        restaurant: 'pista-house-restaurant-&-bakery-madhapur-madhapur',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        '16-11-729, Dilsukhnagar, Gaddiannaram, Malakpet Circle No 6, Hyderabad, Telangana',
      locality: 'Dilsukhnagar',
      parentId: 319765,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 4100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4100,
        message: '',
        title: 'Delivery Charge',
        amount: '4100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '4.5 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '50% OFF',
        subHeader: 'UPTO ₹100',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '700497',
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        lastMileTravel: 4.599999904632568,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '10882',
      name: 'Madhur Sweets',
      uuid: '241920ad-fe43-46a9-9307-31cf4b4cbab3',
      city: '3',
      area: 'Masab Tank',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'y8iljdwvxte9e7rarib7',
      cuisines: ['Sweets', 'Desserts', 'Snacks'],
      tags: [],
      costForTwo: 25000,
      costForTwoString: '₹250 FOR TWO',
      deliveryTime: 42,
      minDeliveryTime: 42,
      maxDeliveryTime: 42,
      slaString: '42 MINS',
      lastMileTravel: 5.699999809265137,
      slugs: {
        restaurant: 'madhur-sweets-humayun-nagar-mehdipatnam',
        city: 'hyderabad',
      },
      cityState: '3',
      address: '10-3-310/B1& 2,Near NMDC,Humayun Nagar,Mehdipatnam',
      locality: 'Humayun Nagar',
      parentId: 1538,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 5400,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 5400,
        message: '',
        title: 'Delivery Charge',
        amount: '5400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7498236~p=16~eid=00000189-879c-0dcc-0030-ddc600f91042~srvts=1690197298636',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '5.6 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '10% OFF',
        subHeader: 'UPTO ₹40',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '10882',
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        lastMileTravel: 5.699999809265137,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.5',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '32129',
      name: 'Burger King',
      uuid: '137eda4d-6758-4002-aa35-c46130fde14b',
      city: '3',
      area: 'Himayatnagar',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'e33e1d3ba7d6b2bb0d45e1001b731fcf',
      cuisines: ['Burgers', 'American'],
      tags: [],
      costForTwo: 35000,
      costForTwoString: '₹350 FOR TWO',
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: '35 MINS',
      lastMileTravel: 2.5999999046325684,
      slugs: {
        restaurant: 'burger-king-mpm-millennium-mall-himayath-nagar',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        'Burger King India Pvt Ltd, Unit No. 104 A, 105 A, 106 & 107, MPM Millennium Mall, GHMC Nos. 3-6-552 to 3-6-558 & 558/1, Himayatnagar Main Road, Himayatnagar, Hyderabad - 500029',
      locality: 'MPM Millennium Mall',
      parentId: 166,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '2.5 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: 'FREE ITEM',
        subHeader: '',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '32129',
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 2.5999999046325684,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '721101',
      name: 'Pista House Bakery',
      uuid: '93a900b2-7943-4868-bcb5-44ca9649a5cf',
      city: '3',
      area: 'Abids & Koti',
      totalRatingsString: 'Too Few Ratings',
      cloudinaryImageId: '6a02cee5c367c438ec8a4becf0b98b1c',
      cuisines: ['Indian', 'Bakery'],
      tags: [],
      costForTwo: 50000,
      costForTwoString: '₹500 FOR TWO',
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: '35 MINS',
      lastMileTravel: 1.2000000476837158,
      slugs: {
        restaurant: 'pista-house-bakery-abids-&-koti-abids-&-koti',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        'Door No. 3-5-142/2 to 4, King Kothi, kothi, Hyderabad-T.S, Goshamahal Circle No. 14, Hyderabad, Telangana',
      locality: 'King Koth',
      parentId: 19008,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.2 kms',
      hasSurge: false,
      sla: {
        restaurantId: '721101',
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 1.2000000476837158,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '--',
      totalRatings: 0,
      new: true,
    },
    subtype: 'basic',
  },
];

const RestaurantCard = ({ restaurant }) => {
  const { name, cloudinaryImageId, cuisines, avgRating, deliveryTime } =
    restaurant.data;
  return (
    <div className="card">
      <img
        src={
          'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/' +
          cloudinaryImageId
        }
      />
      <h2>{name}</h2>
      <h3>{cuisines}</h3>
      <h4>{avgRating} stars</h4>
      <h5>{deliveryTime} minutes</h5>
    </div>
  );
};

const Body = () => {
  return (
    <div className="restaurant__list">
      <RestaurantCard restaurant={restaurantList[0]} />
      <RestaurantCard restaurant={restaurantList[1]} />
      <RestaurantCard restaurant={restaurantList[2]} />
      <RestaurantCard restaurant={restaurantList[3]} />
      <RestaurantCard restaurant={restaurantList[4]} />
      <RestaurantCard restaurant={restaurantList[5]} />
      <RestaurantCard restaurant={restaurantList[6]} />
      <RestaurantCard restaurant={restaurantList[7]} />
      <RestaurantCard restaurant={restaurantList[8]} />
      <RestaurantCard restaurant={restaurantList[9]} />
      <RestaurantCard restaurant={restaurantList[10]} />
      <RestaurantCard restaurant={restaurantList[11]} />
      <RestaurantCard restaurant={restaurantList[12]} />
      <RestaurantCard restaurant={restaurantList[13]} />
      <RestaurantCard restaurant={restaurantList[14]} />
    </div>
  );
};

const Footer = () => {
  return <h4>Footer</h4>;
};

const AppLayout = () => {
  return (
    <React.Fragment>
      <Header />
      <Body />
      <Footer />
    </React.Fragment>
  );
};
const root = ReactDOM.createRoot(document.getElementById('root'));

// passing a react element inside the root
root.render(<AppLayout />);
